# ===============================
# AcademicPages / Jekyll Config
# ===============================

# --- Basic Site Settings ---
locale         : "en-US"
site_theme     : "default"   # "default" or "air"
title          : "Mark Agban — Engineering Portfolio"
title_separator: "-"
name           : &name "Mark Agban"
description    : &description "Aerospace engineer — design, manufacturing, and hands-on projects."
url            : "https://markoa24-portfolio.github.io"   # host for a project site
baseurl        : "/markagban.github.io"                   # repo name with leading slash
repository     : "markoa24-portfolio/markagban.github.io"

# --- Sidebar / Author Profile ---
author:
  avatar     : "profile.png"
  name       : "Mark Agban"
  pronouns   :
  bio        : "UCLA MS Aerospace • Subsystem Design • Manufacturing • Accessibility engineering."
  location   : "Los Angeles, CA"
  employer   : "Lockheed Martin / UCLA"
  uri        :
  email      : "markagban@gmail.com"

  # Repositories and software development
  github     : "markoa24-portfolio"

  # Social media (fill any you want)
  linkedin   : "markagban"
  bluesky    :
  twitter    :

# --- Publication Categories (optional text labels) ---
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# --- Site Settings ---
teaser             :
breadcrumbs        : false
words_per_minute   : 160
future             : true
read_more          : "disabled"
talkmap_link       : false

comments:
  provider         :    # false (default), "disqus", "discourse", etc.
  disqus:
    shortname      :
  discourse:
    server         :
  facebook:
    appid          :
    num_posts      :
    colorscheme    :

staticman:
  allowedFields    : ['name','email','url','message']
  branch           : "gh-pages"
  commitMessage    : "New comment."
  filename         : "comment-{@timestamp}"
  format           : "yml"
  moderation       : true
  path             : "_data/comments/{options.slug}"
  requiredFields   : ['name','email','message']
  transforms:
    email          : "md5"
  generatedFields:
    date:
      type         : "date"
      options:
        format     : "iso8601"

atom_feed:
  hide             : false
  path             :

# --- SEO / Social Preview (optional) ---
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
og_image                 :
og_description           :

# --- Analytics (optional) ---
analytics:
  provider         : "false"   # "google", "google-analytics-4", etc.
  google:
    tracking_id    :

# --- Reading Files ---
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding      : "utf-8"
markdown_ext  : "markdown,mkdown,mkdn,mkd,md"

# --- Conversion ---
markdown          : kramdown
highlighter       : rouge
lsi               : false
excerpt_separator : "\n\n"
incremental       : false

# --- Markdown Processing ---
kramdown:
  input        : GFM
  hard_wrap    : false
  auto_ids     : true
  footnote_nr  : 1
  entity_output: as_char
  toc_levels   : 1..6
  smart_quotes : lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# --- Collections ---
collections:
  teaching:
    output   : true
    permalink: /:collection/:path/
  publications:
    output   : true
    permalink: /:collection/:path/
  portfolio:
    output   : true
    permalink: /:collection/:path/
  talks:
    output   : true
    permalink: /:collection/:path/

# --- Defaults for each collection/page type ---
defaults:
  - scope:
      path : ""
      type : posts
    values:
      layout        : single
      author_profile: true
      read_time     : true
      comments      : true
      share         : true
      related       : true
  - scope:
      path : ""
      type : pages
    values:
      layout        : single
      author_profile: true
  - scope:
      path : ""
      type : teaching
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : true
  - scope:
      path : ""
      type : publications
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : true
  - scope:
      path : ""
      type : portfolio
    values:
      layout        : single
      author_profile: true
      share         : true
      comment       : true
  - scope:
      path : ""
      type : talks
    values:
      layout        : talk
      author_profile: true
      share         : true

# --- Sass/SCSS ---
sass:
  sass_dir: _sass
  style  : compressed

# --- Output / Permalinks ---
permalink: /:categories/:title/
timezone : Etc/UTC

# --- Plugins (GitHub Pages–compatible) ---
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# --- Archives (optional pages) ---
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# --- HTML Compression ---
compress_html:
  clippings: all
  ignore:
    envs: development
